name: Quick Math CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # Specify OS system

    strategy:
      matrix:
        node-version: [16.x] # Specify Node Version
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm ci
      # - run: npm run build --if-present
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Unit Test
        run: yarn test:ci
